from pydantic import BaseModel, EmailStr, Field, field_validator

from app.schemas.common import SafeFullName, SafeName
from app.schemas.student import ChildRegisterCreate, GuardianCreate, StudentResponse


def _normalize_email(value: str) -> str:
    """Trim whitespace and lowercase so lookups never miss on case/space."""
    return value.strip().lower()


class UserCreate(BaseModel):
    email: EmailStr
    password: str = Field(min_length=8, max_length=128)
    full_name: SafeFullName
    role: str = Field(default="parent", pattern="^(admin|finance|parent|super_admin)$")

    @field_validator("email")
    @classmethod
    def _email_norm(cls, v: str) -> str:
        return _normalize_email(v)


class UserResponse(BaseModel):
    id: str
    email: str
    full_name: str
    phone: str | None = None
    role: str
    is_active: bool

    model_config = {"from_attributes": True}


class UserUpdate(BaseModel):
    """Self-service profile update. Any authenticated user can update their
    own name, email and phone. Email must stay unique across the platform."""

    full_name: SafeFullName | None = None
    email: EmailStr | None = None
    phone: str | None = Field(default=None, max_length=50)

    @field_validator("email")
    @classmethod
    def _email_norm(cls, v: str | None) -> str | None:
        if v is None:
            return None
        return _normalize_email(v)


class ParentRegisterCreate(BaseModel):
    """Combined first-time parent registration: portal account + the student
    application being submitted in the same form.

    - email/password: the parent's portal account credentials
    - first_name/last_name: the registering parent's split names
    - phone: parent's contact number (also stored on their guardian record)
    - physical_address/po_box: parent's residential address
    - relationship: the registering parent is the child's father or mother
    - student: the child being applied for (number is generated by the system)
    - additional_students: extra children applied for in the same submission
      (optional — a parent with more than one child can register them together)
    - other_parent: the other parent's details (optional — only one parent is
      required to submit the application)
    """

    email: EmailStr
    password: str = Field(min_length=8, max_length=128)
    first_name: SafeName
    last_name: SafeName
    phone: str | None = Field(default=None, max_length=50)
    physical_address: str | None = Field(default=None, max_length=255)
    po_box: str | None = Field(default=None, max_length=100)
    relationship: str = Field(default="father", pattern="^(father|mother)$")
    student: ChildRegisterCreate
    additional_students: list[ChildRegisterCreate] = Field(default_factory=list, max_length=10)
    other_parent: GuardianCreate | None = None

    @field_validator("email")
    @classmethod
    def _email_norm(cls, v: str) -> str:
        return _normalize_email(v)


class ParentRegisterResponse(BaseModel):
    """Returned after a combined registration so the parent immediately sees
    the generated student numbers and that the applications are pending. The
    access_token logs the parent in so they can upload application documents
    right away."""

    user: UserResponse
    students: list[StudentResponse]
    access_token: str


class Token(BaseModel):
    access_token: str
    token_type: str = "bearer"


class LoginRequest(BaseModel):
    email: EmailStr
    password: str = Field(min_length=1)

    @field_validator("email")
    @classmethod
    def _email_norm(cls, v: str) -> str:
        return _normalize_email(v)


class PasswordChange(BaseModel):
    current_password: str = Field(min_length=1)
    new_password: str = Field(min_length=8, max_length=128)


class ForgotPasswordRequest(BaseModel):
    email: EmailStr

    @field_validator("email")
    @classmethod
    def _email_norm(cls, v: str) -> str:
        return _normalize_email(v)


class ResetPasswordRequest(BaseModel):
    token: str = Field(min_length=1)
    new_password: str = Field(min_length=8, max_length=128)


class ForgotPasswordResponse(BaseModel):
    detail: str
    # Never populated in production. Only set when RESET_TOKEN_IN_RESPONSE
    # is explicitly enabled for local development (token is then also
    # printed to the backend log). Email delivery is the intended path.
    reset_token: str | None = None
