import { useEffect, useState } from 'react';
import { financialApi, studentsApi, gradesApi } from '@/api/client';
import type { Student, Statement, Grade } from '@/types';
import { useAuth } from '@/contexts/AuthContext';
import toast from 'react-hot-toast';
import { FileText } from 'lucide-react';

const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];

export default function StatementsPage() {
  const { user } = useAuth();
  const isParent = user?.role === 'parent';
  const [students, setStudents] = useState<Student[]>([]);
  const [grades, setGrades] = useState<Grade[]>([]);
  const [selectedGrade, setSelectedGrade] = useState('');
  const [selectedStudent, setSelectedStudent] = useState('');
  const [year, setYear] = useState(new Date().getFullYear());
  const [statements, setStatements] = useState<Statement[]>([]);
  const [selectedStatement, setSelectedStatement] = useState<Statement | null>(null);
  const [generating, setGenerating] = useState(false);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    // Parents only ever see their own children (the backend enforces this too).
    studentsApi.list(isParent ? { parent_id: user!.id } : {}).then((r) => {
      setStudents(r.data);
      // Auto-select the first child so a parent sees statements immediately.
      if (isParent && r.data.length > 0) setSelectedStudent(r.data[0].id);
    });
    gradesApi.list().then((r) => setGrades(r.data));
  }, []);

  const filteredStudents = selectedGrade
    ? students.filter((s) => s.grade_id === selectedGrade)
    : students;

  const loadStatements = () => {
    if (!selectedStudent) return;
    setLoading(true);
    financialApi.listStatements(selectedStudent, year).then((r) => setStatements(r.data)).finally(() => setLoading(false));
  };

  useEffect(() => { loadStatements(); }, [selectedStudent, year]);

  const handleGenerate = async (month: number) => {
    if (!selectedStudent) return toast.error('Select a student');
    setGenerating(true);
    try {
      const res = await financialApi.generateStatement({ student_id: selectedStudent, academic_year: year, month });
      toast.success('Statement generated');
      setSelectedStatement(res.data);
      loadStatements();
    } catch {
      toast.error('Generation failed');
    } finally {
      setGenerating(false);
    }
  };

  const getStudentName = (id: string) => {
    const s = students.find((s) => s.id === id);
    return s ? `${s.first_name} ${s.last_name}` : id;
  };

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold text-gray-900">{isParent ? 'My Statements' : 'Student Statements'}</h1>

      <div className="flex gap-4">
        {!isParent && (
          <select value={selectedGrade} onChange={(e) => { setSelectedGrade(e.target.value); setSelectedStudent(''); }} className="rounded-lg border border-gray-300 px-3 py-2 text-sm">
            <option value="">All Grades</option>
            {grades.map((g) => <option key={g.id} value={g.id}>{g.name}</option>)}
          </select>
        )}
        <select value={selectedStudent} onChange={(e) => setSelectedStudent(e.target.value)} className="rounded-lg border border-gray-300 px-3 py-2 text-sm">
          <option value="">{isParent ? 'Select child' : 'Select Student'}</option>
          {filteredStudents.map((s) => <option key={s.id} value={s.id}>{s.first_name} {s.last_name} ({s.student_number})</option>)}
        </select>
        <input type="number" value={year} onChange={(e) => setYear(parseInt(e.target.value))} className="w-32 rounded-lg border border-gray-300 px-3 py-2 text-sm" />
      </div>

      {isParent && (
        <p className="text-sm text-gray-500">
          Statements are generated by the school's finance office. If a month is missing, please contact the office.
        </p>
      )}

      {!isParent && (
        <div className="flex flex-wrap gap-2">
          {MONTHS.map((name, i) => (
            <button
              key={i}
              onClick={() => handleGenerate(i + 1)}
              disabled={generating}
              className="rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50"
            >
              {name}
            </button>
          ))}
        </div>
      )}

      {selectedStatement && (
        <div className="rounded-xl bg-white p-6 shadow-sm border border-gray-100">
          <div className="mb-4 flex items-center justify-between">
            <h2 className="text-lg font-semibold">Statement — {MONTHS[selectedStatement.month - 1]} {selectedStatement.academic_year}</h2>
            <button onClick={() => window.print()} className="flex items-center gap-2 rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50">
              <FileText className="h-4 w-4" /> Print / Export PDF
            </button>
          </div>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div className="space-y-2">
              <Row label="Student" value={getStudentName(selectedStatement.student_id)} />
              <Row label="Opening Balance" value={`R ${selectedStatement.opening_balance.toLocaleString()}`} />
              <Row label="Total Annual Fees" value={`R ${selectedStatement.total_fees.toLocaleString()}`} />
              <Row label="Monthly Installment" value={`R ${selectedStatement.total_installments.toLocaleString()}`} />
            </div>
            <div className="space-y-2">
              <Row label="Additional Charges" value={`R ${selectedStatement.total_additional_charges.toLocaleString()}`} />
              <Row label="Payments Received" value={`R ${selectedStatement.total_payments.toLocaleString()}`} />
              <Row label="Closing Balance" value={`R ${selectedStatement.closing_balance.toLocaleString()}`} highlight />
              <Row label="Amount Due" value={`R ${selectedStatement.current_amount_due.toLocaleString()}`} highlight />
              <Row label="Due Date" value={new Date(selectedStatement.due_date).toLocaleDateString()} />
            </div>
          </div>
        </div>
      )}

      <div className="rounded-xl bg-white shadow-sm border border-gray-100 overflow-hidden">
        {loading ? (
          <div className="flex h-32 items-center justify-center">
            <div className="h-6 w-6 animate-spin rounded-full border-4 border-primary-500 border-t-transparent" />
          </div>
        ) : (
          <>
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Month</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Installment</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Payments</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Closing Balance</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Generated</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200">
            {statements.map((s) => (
              <tr key={s.id} className="cursor-pointer hover:bg-gray-50" onClick={() => setSelectedStatement(s)}>
                <td className="px-6 py-4 text-sm font-medium text-gray-900">{MONTHS[s.month - 1]}</td>
                <td className="px-6 py-4 text-sm text-gray-700">R {s.total_installments.toLocaleString()}</td>
                <td className="px-6 py-4 text-sm text-green-600">R {s.total_payments.toLocaleString()}</td>
                <td className="px-6 py-4 text-sm font-medium text-gray-900">R {s.closing_balance.toLocaleString()}</td>
                <td className="px-6 py-4 text-sm text-gray-500">{new Date(s.generated_at).toLocaleDateString()}</td>
              </tr>
            ))}
          </tbody>
        </table>
        {statements.length === 0 && !loading && <p className="py-8 text-center text-sm text-gray-500">{selectedStudent ? (isParent ? 'No statements generated for this child yet.' : 'No statements. Generate one above.') : 'Select a student.'}</p>}
          </>
        )}
      </div>
    </div>
  );
}

function Row({ label, value, highlight }: { label: string; value: string; highlight?: boolean }) {
  return (
    <div className="flex justify-between border-b border-gray-100 py-2">
      <span className="text-sm text-gray-500">{label}</span>
      <span className={`text-sm font-medium ${highlight ? 'text-primary-700' : 'text-gray-900'}`}>{value}</span>
    </div>
  );
}
